In [1]:
#pip install matplotlib

In [2]:
words = open('names.txt', 'r').read().splitlines()

In [3]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [4]:
len(words)

32033

In [5]:
min(len(w) for w in words)

2

In [6]:
max(len(w) for w in words)

15

In [7]:
b = {}
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs,chs[1:]):
        bigram = (ch1,ch2)
        b[bigram] = b.get(bigram,0) +1

In [8]:
w, list(w)

('zzyzx', ['z', 'z', 'y', 'z', 'x'])

In [9]:
sorted(b.items(),key = lambda kv: -kv[1])

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [10]:
import torch

In [11]:
N = torch.zeros((27,27), dtype = torch.int32)

In [12]:
chars = sorted(list(set(''.join(words)) ))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0

In [13]:


stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [14]:
for w in words:#we need integers instead of list characters
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1
        

In [15]:
itos = {i:s for s,i in stoi.items()}


In [16]:
# import matplotlib.pyplot as plt
# %matplotlib inline

# plt.figure(figsize=(8,8))
# plt.imshow(N, cmap = 'Blues')
# for i in range(28):
#     for j in range(28):
#         chstr = itos[i] + itos[j]
# #        plt.text(j,i,chstr, ha="center", va="bottom", color = 'gray')
# #        plt.text(j,i, N[i,j].item(), ha="center", va="top", color='gray')
# plt.axis('off');

In [17]:
N[0]


tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [27]:
p = N[0].float()
p = p / p.sum() # here gets the probability distribution
p



tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [28]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'j'

In [24]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p/p.sum()
p


tensor([0.6064, 0.3033, 0.0903])

In [25]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [35]:
p.shape

torch.Size([27])

In [41]:
P.shape

torch.Size([27, 27])

In [43]:
P.sum(1, keepdim=True).shape

torch.Size([27, 1])

In [69]:
P = (N+1).float() #addig  1 later on as to smooth the model to ensure no 0 in our probabiility matrix
P = P/P.sum(1, keepdim=True)

In [70]:
P[0].sum()

tensor(1.)

In [71]:
g = torch.Generator().manual_seed(2147483647)

#Broadasting Documentation from Pytorch go through it and practise
for i in range(5):
        
    out = []
    ix = 0 
    while True:
        p = P[ix]
        # p = N[ix].float() #bigramshere
        # p = p/p.sum()
        #p = torch.ones(27)/27.0#uniform distribution
        ix = torch.multinomial(p,num_samples = 1, replacement = True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))


junide.
janasah.
p.
cony.
a.


In [72]:
log_likelihood = 0.0
n = 0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1,ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1,ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n+=1
        print(f'{ch1}{ch2} : {prob:.4f} {logprob : .4f}')
print(f'{log_likelihood = }')
negative_LogLikelihood = -log_likelihood
print(f'{negative_LogLikelihood}')
print(f'{negative_LogLikelihood/n}') # taking an average and this will be out loss_function so lower it is best it is
#so minimum negative_LogLikelihood can get is 0 and is best
#if its max, the worse the training is done on model

.e : 0.0478 -3.0410
em : 0.0377 -3.2793
mm : 0.0253 -3.6753
ma : 0.3885 -0.9454
a. : 0.1958 -1.6305
.o : 0.0123 -4.3965
ol : 0.0779 -2.5526
li : 0.1774 -1.7293
iv : 0.0152 -4.1845
vi : 0.3508 -1.0476
ia : 0.1380 -1.9807
a. : 0.1958 -1.6305
.a : 0.1376 -1.9835
av : 0.0246 -3.7041
va : 0.2473 -1.3971
a. : 0.1958 -1.6305
log_likelihood = tensor(-38.8086)
38.80856704711914
2.4255354404449463


In [73]:
#Checking the likelihood prob for any name
log_likelihood = 0.0
n = 0
#for w in words:
for w in ["maharshiqz"]:#qz is 0 percent chance to occure together in our dataset
    chs = ['.'] + list(w) + ['.']
    for ch1,ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1,ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n+=1
        print(f'{ch1}{ch2} : {prob:.4f} {logprob : .4f}')
print(f'{log_likelihood = }')
negative_LogLikelihood = -log_likelihood
print(f'{negative_LogLikelihood}')
print(f'{negative_LogLikelihood/n}') # taking an average and this will be out loss_function so lower it is best it is
#so minimum negative_LogLikelihood can get is 0 and is best
#if its max, the worse the training is done on model

.m : 0.0792 -2.5358
ma : 0.3885 -0.9454
ah : 0.0688 -2.6766
ha : 0.2937 -1.2251
ar : 0.0963 -2.3405
rs : 0.0150 -4.1992
sh : 0.1581 -1.8444
hi : 0.0955 -2.3485
iq : 0.0030 -5.8126
qz : 0.0033 -5.7004
z. : 0.0664 -2.7122
log_likelihood = tensor(-32.3408)
32.3408088684082
2.9400734901428223


In [80]:
#create the training set of all the bigrams
xs, ys = [], []

for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1,ch2)
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys =  torch.tensor(ys)
    

. e
e m
m m
m a
a .


In [81]:
xs 

tensor([ 0,  5, 13, 13,  1])

In [82]:
import torch.nn.functional as F


In [86]:
xenc = F.one_hot(xs, num_classes=27).float() #this is the input to the neural nets
xenc.shape

torch.Size([5, 27])

In [87]:
xenc.dtype

torch.float32

In [89]:
W = torch.randn((27,27))
xenc @ W # @ is matrix multiplication in torch

tensor([[-4.1495e-01, -5.5955e-01, -3.8064e+00,  1.7192e-01,  5.6901e-01,
         -6.4085e-01,  1.0497e+00, -4.2916e-01,  4.3641e-01, -6.5378e-01,
         -4.8888e-01,  1.0694e+00, -1.3716e-01, -3.5755e+00, -1.7083e+00,
          1.0365e-01,  3.7659e-01, -2.3428e+00, -1.3350e+00,  1.7162e+00,
          3.4640e-01, -1.3093e+00, -8.4605e-01,  1.6179e+00,  8.4872e-01,
          6.9486e-01, -6.0509e-01],
        [ 9.1716e-01, -1.4508e+00,  3.0025e-01,  1.6484e+00, -4.9083e-01,
          1.8067e-01,  8.0592e-01, -5.7641e-01,  2.7751e+00,  1.4579e+00,
          5.5928e-01, -3.4976e-01, -1.0891e+00,  5.1675e-01,  1.0232e+00,
          6.9597e-01,  1.6482e+00,  5.9230e-01,  4.0637e-01,  2.1469e+00,
          6.7002e-01, -5.3360e-01,  8.6646e-02,  1.5369e-01, -5.8565e-01,
         -5.9139e-01,  1.9511e-01],
        [-1.3876e+00,  2.9071e-01,  1.0114e+00,  4.9748e-01, -7.3147e-01,
          5.2941e-01, -7.1417e-01, -1.7931e+00,  1.1603e-01, -1.1087e+00,
          3.3906e-03,  6.7150e-01,  1.92

In [90]:
(xenc @ W).exp()

tensor([[ 0.6604,  0.5715,  0.0222,  1.1876,  1.7665,  0.5268,  2.8567,  0.6511,
          1.5471,  0.5201,  0.6133,  2.9137,  0.8718,  0.0280,  0.1812,  1.1092,
          1.4573,  0.0961,  0.2632,  5.5633,  1.4140,  0.2700,  0.4291,  5.0425,
          2.3367,  2.0034,  0.5460],
        [ 2.5022,  0.2344,  1.3502,  5.1988,  0.6121,  1.1980,  2.2388,  0.5619,
         16.0397,  4.2968,  1.7494,  0.7049,  0.3365,  1.6766,  2.7820,  2.0057,
          5.1976,  1.8081,  1.5014,  8.5582,  1.9543,  0.5865,  1.0905,  1.1661,
          0.5567,  0.5536,  1.2154],
        [ 0.2497,  1.3374,  2.7495,  1.6446,  0.4812,  1.6979,  0.4896,  0.1664,
          1.1230,  0.3300,  1.0034,  1.9572,  6.8214,  0.4059,  8.2466,  4.0972,
          0.1023,  0.0504,  0.6549,  1.4943,  4.7218,  3.0300,  4.0426,  0.1741,
          0.6547,  1.9865,  2.0051],
        [ 0.2497,  1.3374,  2.7495,  1.6446,  0.4812,  1.6979,  0.4896,  0.1664,
          1.1230,  0.3300,  1.0034,  1.9572,  6.8214,  0.4059,  8.2466,  4.0972

In [104]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), generator = g, requires_grad = True)

In [105]:
#Forward Pass

logits = xenc@W # predicts the log count
counts = logits.exp() #same as N, are positive softmax function
probs = counts /counts.sum(1, keepdims=True) # softmax function and gives probability for next character
#counts and probs are combined to form softmax function
loss = -probs[torch.arange(5), ys].log().mean()


In [106]:
#probs[0,5], probs[1,13], probs[2,13], probs[3,1], probs[4,0]

In [107]:
#Backward pass

W.grad = None # gradient set to 0
loss.backward() # fills the gradients 


In [112]:
W.data += -1.0 * W.grad

In [113]:
# ------------!!! OPTIMIZING ALL NOW

In [117]:
#create the dataset
xs, ys = [],[]
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        ys.append(ix2)
        xs.append(ix1)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples : ', num)

# initilizing the network
g = torch.Generator(). manual_seed(2147483647)
W = torch.randn((27,27), generator = g , requires_grad=True)


number of examples :  228146


In [128]:
#gradient descent
for k in range(2000):
    #forward pass
    xenc = F.one_hot(xs, num_classes=27).float() # input to the network
    logits = xenc @ W #predicts the log-counts
    counts = logits.exp() # +ve making of logits
    probs = counts/ counts.sum(1, keepdims = True) #probabilities for the next character
    loss = -probs[torch.arange(num), ys].log().mean()
    print(loss.item())

    #backward pass
    W.grad = None #setting gradient to zero
    loss.backward()

    #update
    W.data += -65 * W.grad
    

2.454468011856079
2.4544677734375
2.4544677734375
2.454467296600342
2.454467296600342
2.454467296600342
2.4544665813446045
2.4544663429260254
2.4544661045074463
2.4544661045074463
2.454465866088867
2.454465627670288
2.454465627670288
2.454464912414551
2.454464912414551
2.4544646739959717
2.4544644355773926
2.4544641971588135
2.4544639587402344
2.4544639587402344
2.4544637203216553
2.454463481903076
2.454463481903076
2.454463005065918
2.454462766647339
2.4544625282287598
2.4544622898101807
2.4544622898101807
2.4544620513916016
2.4544618129730225
2.4544618129730225
2.454461097717285
2.454461097717285
2.454460859298706
2.454460859298706
2.454460620880127
2.454460382461548
2.4544601440429688
2.4544599056243896
2.4544599056243896
2.4544594287872314
2.4544591903686523
2.4544589519500732
2.454458713531494
2.454458713531494
2.454458475112915
2.454458236694336
2.454457998275757
2.454457998275757
2.4544575214385986
2.4544572830200195
2.4544572830200195
2.4544568061828613
2.4544568061828613
2.454